server:
  port: 8080
  servlet:
    context-path: /yxyz
spring:
  datasource:
    name: yxyz
    url: jdbc:mysql://localhost:3306/springboot_demo?serverTimezone=GMT%2b8
    username: root
    password: 19961117Lhh
 # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
## 该配置节点为独立的节点
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.yxyz.vo # 注意：对应实体类的路径
